version: "3"

# Services object represent different containers to be runed
services:
  # Web represent the app container
  web:
    # Point to Dockerfile
    build: .

    # Port forwarding configuration
    ports:
      - "8080:8080"

  # Represent database container
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

# Store data across multiple container
volumes:
  db-data:
